-- Fix leads table
ALTER TABLE leads 
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `area_id` INTEGER NULL;

-- Fix expenses table
ALTER TABLE expenses
  ADD COLUMN IF NOT EXISTS `is_recurring` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS `frequency` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `due_day` INTEGER NULL,
  ADD COLUMN IF NOT EXISTS `next_due` DATETIME(3) NULL,
  ADD COLUMN IF NOT EXISTS `last_paid` DATETIME(3) NULL;

-- Fix users table
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS `plain_password` VARCHAR(191) NULL;
