-- Run this SQL on your MySQL database if prisma migrate is not used

ALTER TABLE leads ADD COLUMN IF NOT EXISTS agreed_amount DECIMAL(10,2) NULL;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS payment_confirmed TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS pending_outcome VARCHAR(50) NULL;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS voice_note TEXT NULL;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lat DOUBLE NULL;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lng DOUBLE NULL;

ALTER TABLE areas ADD COLUMN IF NOT EXISTS lat DOUBLE NULL;
ALTER TABLE areas ADD COLUMN IF NOT EXISTS lng DOUBLE NULL;

ALTER TABLE workshop_jobs ADD COLUMN IF NOT EXISTS delivery_assigned_to INT NULL;
ALTER TABLE workshop_jobs ADD COLUMN IF NOT EXISTS delivery_assigned_at DATETIME NULL;

CREATE TABLE IF NOT EXISTS technician_settlements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  technician_id INT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  description VARCHAR(255) NULL,
  lead_id INT NULL,
  is_received TINYINT(1) NOT NULL DEFAULT 0,
  received_at DATETIME NULL,
  received_by INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
